import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  facts: [
    "Mısır piramitleri yaklaşık 4,500 yıl önce inşa edilmiştir.",
    "Dünyanın en uzun nehri Nil Nehri'dir.",
    "Çin Seddi, yaklaşık 21,196 kilometre uzunluğundadır.",
    "Dünyanın en kalabalık ülkesi Çin'dir.",
    "İlk modern olimpiyatlar 1896'da Atina'da yapıldı.",
    "Everest Dağı, dünyanın en yüksek zirvesidir.",
    "Dünya'nın en büyük çölü, Antarktika Çölü'dür.",
    "Venüs gezegeni saat yönünde dönen tek gezegendir.",
    "Ay, Dünya'nın tek doğal uydusudur.",
    "Machu Picchu, Peru'da yer alan eski bir İnka şehridir.",
    "Japonya, 6,852 adadan oluşan bir takımadadır.",
    "Babil'in Asma Bahçeleri, antik dünyanın yedi harikasından biridir.",
    "Sahra Çölü, dünyadaki en sıcak çöldür.",
    "Galapagos Adaları, Darwin'in evrim teorisine ilham vermiştir.",
    "Taj Mahal, Hindistan'da yer alan beyaz mermerden yapılmış bir anıttır.",
    "Mona Lisa, Leonardo da Vinci tarafından yapılmış bir tablodur.",
    "Big Ben, Londra'da yer alan ünlü bir saat kulesidir.",
    "Eiffel Kulesi, Paris'in simgesel yapılarından biridir.",
    "Amazon Yağmur Ormanları, dünyanın en büyük tropikal ormanıdır.",
    "Greenwich Gözlemevi, sıfır meridyenin geçtiği yerdir.",
    "İstanbul, hem Asya hem de Avrupa'da yer alan tek şehirdir.",
    "Victoria Şelalesi, Zambezi Nehri üzerinde yer alır.",
    "Galata Kulesi, İstanbul'da yer alan tarihi bir kuledir.",
    "Kleopatra, Mısır'ın son Firavun'uydu.",
    "İskenderiye Kütüphanesi, antik dünyanın en büyük kütüphanesiydi.",
    "Berlin Duvarı, 1989'da yıkılmıştır.",
    "Colosseum, Roma'da yer alan antik bir arenadır.",
    "Aztekler, Meksika'da büyük bir medeniyet kurmuşlardır.",
    "Atina, Yunanistan'ın başkentidir.",
    "Büyük Kanyon, Amerika Birleşik Devletleri'nde yer alır.",
    "Venedik, kanallarıyla ünlü bir İtalyan şehridir.",
    "Mikronesiya, Pasifik Okyanusu'nda yer alan bir ada ülkesidir.",
    "Piramitler, Giza'da yer alan ünlü yapılar arasındadır.",
    "İngiltere, Londra'nın başkentidir.",
    "Beyaz Saray, Amerika Birleşik Devletleri başkanının resmi konutudur.",
    "Hollywood, film endüstrisinin merkezi olarak bilinir.",
    "Sidney Opera Evi, Avustralya'nın sembolik yapılarından biridir.",
    "İzlanda, volkanları ve gayzerleri ile ünlüdür.",
    "Kutup Ayıları, yalnızca Kuzey Kutbu'nda yaşar.",
    "Yosemite Ulusal Parkı, Amerika Birleşik Devletleri'nde yer alır.",
    "Galata Köprüsü, İstanbul'da Haliç üzerine kurulmuştur.",
    "Trans-Sibirya Demiryolu, dünyanın en uzun demiryolu hattıdır.",
    "Niagara Şelalesi, Amerika ve Kanada sınırında yer alır.",
    "Mount Fuji, Japonya'nın en yüksek dağıdır.",
    "Antik Yunan'da Olimpiyat Oyunları, tanrı Zeus onuruna düzenlenirdi.",
    "Stonehenge, İngiltere'de yer alan tarih öncesi bir anıttır.",
    "Büyük Set Resifi, dünyanın en büyük mercan resifidir.",
    "Everest Dağı, 8,848 metre yüksekliğindedir.",
    "Kudüs, üç büyük dinin kutsal şehri olarak bilinir.",
    "Pasifik Okyanusu, dünyanın en büyük okyanusudur.",
    "Sibirya, Rusya'nın büyük bir kısmını kaplar.",
    "Himalayalar, dünyanın en yüksek dağ sırasıdır.",
    "Nile Nehri, Afrika kıtasında akar.",
    "Roma İmparatorluğu, Batı Avrupa'da büyük bir imparatorluktu.",
    "Şangay, Çin'in en büyük şehirlerinden biridir.",
    "İran, eski adıyla Pers İmparatorluğu olarak bilinir.",
    "Amazon Nehri, dünyanın en büyük nehri olarak kabul edilir.",
    "Gobi Çölü, Asya'nın büyük çöllerindendir.",
    "Galileo Galilei, modern bilimin babası olarak bilinir.",
    "Yedi Harikalar'dan biri olan Artemis Tapınağı, Efes'te yer alır.",
    "Zürih, İsviçre'nin finans merkezi olarak bilinir.",
    "Maldivler, Hint Okyanusu'nda yer alan bir ada ülkesidir.",
    "Şili, dünyanın en uzun ülkelerinden biridir.",
    "Sagrada Familia, Barcelona'da yer alan ünlü bir bazilikadır.",
    "Kenya, vahşi yaşamı ile ünlüdür.",
    "Patagonya, Güney Amerika'nın güneyinde yer alır.",
    "Fransa, Eyfel Kulesi ile ünlüdür.",
    "Endonezya, 17,000'den fazla adaya sahiptir.",
    "Norveç, fiyortları ile ünlüdür.",
    "Hindistan, dünyanın en büyük demokrasisidir.",
    "Sahara Çölü, Afrika kıtasında yer alır.",
    "İstanbul Boğazı, Asya ve Avrupa'yı ayırır.",
    "Çin Seddi, 7. yüzyılda inşa edilmeye başlanmıştır.",
    "Şili, Atacama Çölü'ne ev sahipliği yapar.",
    "Avustralya, kıta ve ülke olarak bilinir.",
    "Kamboçya, Angkor Wat Tapınağı ile ünlüdür.",
    "Afrika, en fazla ülkeye sahip kıtadır.",
    "Finlandiya, binlerce göle sahip bir ülkedir.",
    "Singapur, Asya'nın en küçük ülkelerindendir.",
    "Hawaii, Amerika Birleşik Devletleri'nin bir eyaletidir.",
    "Yeni Zelanda, Hobbit filmi çekim yerlerinden biridir.",
    "Peru, İnka İmparatorluğu'nun merkeziydi.",
    "Yunanistan, demokrasinin doğum yeri olarak bilinir.",
    "Viyana, Avusturya'nın başkentidir.",
    "Küba, Karayipler'de yer alan bir ada ülkesidir.",
    "Birleşik Arap Emirlikleri, petrol zenginidir.",
    "Kenya, Maasai Mara Milli Parkı ile ünlüdür.",
    "Bolivya, Güney Amerika'nın merkezindedir.",
    "Nepal, Everest Dağı'na ev sahipliği yapar.",
    "İsviçre, Alpler ile ünlüdür.",
    "Macaristan, Budapeşte'nin başkentidir.",
    "Pakistan, Himalaya Dağları'nın bir kısmını içerir.",
    "Portekiz, Lizbon'un başkentidir.",
    "Danimarka, Kopenhag'ın başkentidir.",
    "Kolombiya, kahvesi ile ünlüdür.",
    "Arjantin, tango dansının doğduğu yerdir.",
    "Endonezya, Bali adasına ev sahipliği yapar.",
    "İspanya, flamenko dansı ile ünlüdür.",
    "Brezilya, Amazon Ormanları'na ev sahipliği yapar.",
    "Hindistan, Tac Mahal ile ünlüdür.",
    "Rusya, dünyanın en büyük yüzölçümüne sahip ülkesidir.",
    "Japonya, çiçek açan kiraz ağaçları ile ünlüdür.",
    "Çin, İpek Yolu'nun başlangıç noktasıydı.",
    "Mısır, firavunlar diyarıdır.",
    "Fransa, Louvre Müzesi'ne ev sahipliği yapar.",
    "İngiltere, Thames Nehri ile bilinir.",
    "İtalya, Pisa Kulesi ile ünlüdür.",
    "Norveç, Kuzey Işıkları ile bilinir.",
    "Almanya, Berlin Duvarı ile ünlüdür.",
    "Kanada, Niagara Şelalesi'ne ev sahipliği yapar.",
    "Meksika, Maya ve Aztek kalıntıları ile bilinir.",
    "Fas, Sahara Çölü'ne komşudur.",
    "İsrail, Kudüs'ün bulunduğu ülkedir.",
    "Suriye, antik Palmyra kentine ev sahipliği yapar.",
    "Lübnan, Beyrut'un başkentidir.",
    "Güney Afrika, Nelson Mandela'nın memleketidir.",
    "Tayland, altın tapınakları ile ünlüdür.",
    "Avustralya, Sidney Limanı Köprüsü ile bilinir.",
    "Yeni Zelanda, Maori kültürü ile ünlüdür.",
    "İsviçre, çikolataları ile ünlüdür.",
    "İzlanda, sıcak su kaynakları ile ünlüdür.",
    "Türkiye, Ayasofya ile ünlüdür.",
    "Yunanistan, Parthenon Tapınağı ile bilinir.",
    "İran, Persepolis antik kentini içerir.",
    "Mısır, Nil Nehri'ni geçer.",
    "Fransa, şarapları ile ünlüdür.",
    "İtalya, Roma İmparatorluğu'nun merkezidir.",
    "Çin, dev pandaları ile ünlüdür.",
    "Brezilya, Rio Karnavalı ile bilinir.",
    "İspanya, boğa güreşleri ile ünlüdür.",
    "Hindistan, Bollywood sineması ile bilinir.",
    "Rusya, Kızıl Meydan'a ev sahipliği yapar.",
    "Japonya, Tokyo Kulesi ile bilinir.",
    "ABD, Beyaz Saray'a ev sahipliği yapar.",
    "Meksika, Teotihuacan piramitleri ile bilinir.",
    "Peru, Machu Picchu ile ünlüdür.",
    "Kanada, CN Kulesi ile bilinir.",
    "Norveç, fiyortları ile bilinir.",
    "Finlandiya, Kuzey Işıkları ile ünlüdür.",
    "İsveç, Stockholm'un başkentidir.",
    "Danimarka, Viking tarihine sahiptir.",
    "Hollanda, yel değirmenleri ile ünlüdür.",
    "İspanya, Sagrada Familia ile bilinir.",
    "Portekiz, Porto şarapları ile ünlüdür.",
    "Yunanistan, Akropolis ile bilinir.",
    "Mısır, Abu Simbel tapınakları ile bilinir.",
    "Hindistan, Himalaya Dağları'na ev sahipliği yapar.",
    "Nepal, Katmandu'nun başkentidir.",
    "Sri Lanka, çay tarlaları ile ünlüdür.",
    "İran, Şiraz şehri ile bilinir.",
    "İzlanda, buz mağaraları ile ünlüdür.",
    "Yunanistan, Girit adası ile bilinir.",
    "İsviçre, Matterhorn Dağı'na ev sahipliği yapar.",
    "Brezilya, Iguazu Şelalesi ile bilinir.",
    "Şili, Paskalya Adası'na ev sahipliği yapar.",
    "Avustralya, Uluru Kayası ile bilinir.",
    "Meksika, Chichen Itza ile bilinir.",
    "İtalya, Venedik kanalları ile ünlüdür.",
    "Hindistan, Ganj Nehri ile bilinir.",
    "Çin, Yasak Şehir ile ünlüdür.",
    "İran, Persepolis ile bilinir.",
    "Mısır, Sfenks ile bilinir.",
    "Fransa, Eyfel Kulesi ile bilinir.",
    "İspanya, Endülüs bölgesi ile ünlüdür.",
    "Japonya, Fuji Dağı ile bilinir.",
    "ABD, Grand Canyon ile ünlüdür.",
    "Kanada, Banff Ulusal Parkı ile bilinir.",
    "Norveç, Bergen şehri ile ünlüdür.",
    "Finlandiya, Laponya bölgesi ile bilinir.",
    "İsveç, Gotland Adası ile ünlüdür.",
    "Danimarka, Legoland ile bilinir.",
    "Hollanda, Amsterdam kanalları ile ünlüdür.",
    "İspanya, Ibiza Adası ile bilinir.",
    "Portekiz, Algarve sahilleri ile ünlüdür.",
    "Yunanistan, Santorini Adası ile bilinir.",
    "Mısır, Luxor Tapınağı ile ünlüdür.",
    "Hindistan, Kerala'nın arka su yolları ile bilinir.",
    "Nepal, Everest Dağı ile ünlüdür.",
    "Sri Lanka, Sigiriya Kayası ile bilinir.",
    "İran, İsfahan'ın başkentidir.",
    "İzlanda, Vatnajökull Buzulu ile ünlüdür.",
    "Yunanistan, Korfu Adası ile bilinir.",
    "İsviçre, Zermatt kayak merkezi ile ünlüdür.",
    "Brezilya, Amazon Nehri ile bilinir.",
    "Şili, Atacama Çölü ile ünlüdür.",
    "Avustralya, Büyük Set Resifi ile bilinir.",
    "Meksika, Cancun sahilleri ile ünlüdür.",
    "İtalya, Roma şehri ile bilinir.",
    "Hindistan, Jaipur'un pembe şehri ile ünlüdür.",
    "Çin, Çin Seddi ile bilinir.",
    "İran, Tahran'ın başkentidir.",
    "Mısır, Kahire Müzesi ile ünlüdür.",
    "Fransa, Paris şehri ile bilinir.",
    "İspanya, La Rambla Caddesi ile ünlüdür.",
    "Japonya, Kyoto'nun tapınakları ile bilinir.",
    "ABD, Las Vegas şehri ile ünlüdür.",
    "Kanada, Toronto şehri ile bilinir.",
    "Norveç, Tromso şehri ile ünlüdür.",
    "Finlandiya, Helsinki şehri ile bilinir.",
    "İsveç, Göteborg şehri ile ünlüdür.",
    "Danimarka, Aarhus şehri ile bilinir.",
    "Hollanda, Rotterdam şehri ile ünlüdür.",
    "İspanya, Valencia şehri ile bilinir.",
    "Portekiz, Porto şehri ile ünlüdür.",
    "Yunanistan, Rodos Adası ile bilinir.",
    "Mısır, Krallar Vadisi ile ünlüdür.",
    "Hindistan, Goa sahilleri ile bilinir.",
    "Nepal, Pokhara şehri ile ünlüdür.",
    "Sri Lanka, Kandy şehri ile bilinir.",
    "İran, Şiraz şehri ile ünlüdür.",
    "İzlanda, Reykjavik şehri ile bilinir.",
    "Yunanistan, Mykonos Adası ile ünlüdür.",
    "İsviçre, Luzern şehri ile bilinir.",
    "Brezilya, Sao Paulo şehri ile ünlüdür.",
    "Şili, Valparaiso şehri ile bilinir.",
    "Avustralya, Melbourne şehri ile ünlüdür.",
    "Meksika, Mexico City şehri ile bilinir.",
    "İtalya, Floransa şehri ile ünlüdür.",
    "Hindistan, Agra şehri ile bilinir.",
    "Çin, Şangay şehri ile ünlüdür.",
    "İran, İsfahan şehri ile bilinir.",
    "Mısır, İskenderiye şehri ile ünlüdür.",
    "Fransa, Nice şehri ile bilinir.",
    "İspanya, Sevilla şehri ile ünlüdür.",
    "Japonya, Osaka şehri ile bilinir.",
    "ABD, New York şehri ile ünlüdür.",
    "Kanada, Vancouver şehri ile bilinir.",
    "Norveç, Oslo şehri ile ünlüdür.",
    "Finlandiya, Rovaniemi şehri ile bilinir.",
    "İsveç, Malmo şehri ile ünlüdür.",
    "Danimarka, Odense şehri ile bilinir.",
    "Hollanda, Utrecht şehri ile ünlüdür.",
    "İspanya, Bilbao şehri ile bilinir.",
    "Portekiz, Lizbon şehri ile ünlüdür.",
    "Yunanistan, Atina şehri ile bilinir.",
    "Mısır, Giza Piramitleri ile ünlüdür.",
    "Hindistan, Varanasi şehri ile bilinir.",
    "Nepal, Lumbini şehri ile ünlüdür.",
    "Sri Lanka, Anuradhapura şehri ile bilinir.",
    "İran, Tebriz şehri ile ünlüdür.",
    "İzlanda, Akureyri şehri ile bilinir.",
    "Yunanistan, Olimpos Dağı ile ünlüdür.",
    "İsviçre, Interlaken kasabası ile bilinir.",
    "Brezilya, Manaus şehri ile ünlüdür.",
    "Şili, Punta Arenas şehri ile bilinir.",
    "Avustralya, Brisbane şehri ile ünlüdür.",
    // Buraya yüzlerce kısa genel kültür bilgisi ekleyin.
  ],
  currentFactIndex: 0,
};

const cultureSlice = createSlice({
  name: 'culture',
  initialState,
  reducers: {
    nextFact: (state) => {
      state.currentFactIndex = (state.currentFactIndex + 1) % state.facts.length;
    },
    randomFact: (state) => {
      state.currentFactIndex = Math.floor(Math.random() * state.facts.length);
    },
  },
});

export const { nextFact, randomFact } = cultureSlice.actions;

export default cultureSlice.reducer;
